version: '3.8'

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb+srv://sorajeev5918:g3u9NH3VKJ45yTKw@cluster0.egtqq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'


  db:
    image: mongo:latest
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=create_alert
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"

volumes:
  mongo_data:
